export const DEFAULT_CODEX_ORIGINATOR = "codex_cli_rs";
export const DEFAULT_CODEX_USER_AGENT_VERSION = "0.153.0";
export const DEFAULT_CODEX_USER_AGENT =
  `${DEFAULT_CODEX_ORIGINATOR}/${DEFAULT_CODEX_USER_AGENT_VERSION}`;
